import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  DIFFICULTY_BASE,
  TASK_COIN_DISCOUNT,
  COMBO_TIERS,
  LEVEL_XP_BASE,
  LEVEL_XP_EXPONENT,
  FREEZE_TOKEN_LEVEL_INTERVAL,
  FREEZE_TOKEN_MAX_BALANCE,
  LEAGUE_TIERS,
  LEAGUE_PROMOTE_TOP,
  LEAGUE_RELEGATE_BOTTOM,
} from "../src/features/gamification/constants";

/**
 * Mirrors src/features/gamification/constants.ts into SQL so the Postgres
 * RPCs and the tested TS lib can never drift (CLAUDE.md: divergence is a
 * breaking bug). Regenerate with `npm run db:gen-sql` whenever constants.ts
 * changes, then re-apply with `npm run db:apply-sql`.
 */

const difficultyCases = Object.entries(DIFFICULTY_BASE)
  .map(([difficulty, base]) => `    when '${difficulty}' then ${base}`)
  .join("\n");

// COMBO_TIERS is ordered highest-min-first, matching the TS lib's first-match iteration.
const comboCases = COMBO_TIERS.map((tier) => `    when streak >= ${tier.min} then ${tier.mult}`).join("\n");

const sql = `-- GENERATED by scripts/gen-sql-constants.ts from src/features/gamification/constants.ts
-- Do not hand-edit. Run \`npm run db:gen-sql\` to regenerate.

create or replace function public.difficulty_base(difficulty text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case difficulty
${difficultyCases}
  end;
$$;

create or replace function public.combo_multiplier(streak int)
returns numeric
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case
${comboCases}
    else 1
  end;
$$;

create or replace function public.task_coins(difficulty text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select round(public.difficulty_base(difficulty) * ${TASK_COIN_DISCOUNT})::int;
$$;

create or replace function public.level_req_for(p_level int)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select round(${LEVEL_XP_BASE} * power(p_level, ${LEVEL_XP_EXPONENT}))::int;
$$;

create or replace function public.level_info(total_xp int)
returns table(level int, into_level int, need int)
language plpgsql
immutable
set search_path = public, pg_catalog
as $$
declare
  v_level int := 1;
  v_remaining int := greatest(0, total_xp);
begin
  while v_remaining >= public.level_req_for(v_level) loop
    v_remaining := v_remaining - public.level_req_for(v_level);
    v_level := v_level + 1;
  end loop;
  return query select v_level, v_remaining, public.level_req_for(v_level);
end;
$$;

create or replace function public.freeze_token_level_interval()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${FREEZE_TOKEN_LEVEL_INTERVAL};
$$;

create or replace function public.freeze_token_max_balance()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${FREEZE_TOKEN_MAX_BALANCE};
$$;

create or replace function public.tokens_earned_between_levels(level_before int, level_after int)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select (level_after / public.freeze_token_level_interval())
       - (level_before / public.freeze_token_level_interval());
$$;

create or replace function public.league_tiers()
returns text[]
language sql
immutable
set search_path = public, pg_catalog
as $$
  select array[${LEAGUE_TIERS.map((t) => `'${t}'`).join(", ")}];
$$;

create or replace function public.league_promote_top()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${LEAGUE_PROMOTE_TOP};
$$;

create or replace function public.league_relegate_bottom()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${LEAGUE_RELEGATE_BOTTOM};
$$;
`;

const outPath = join(__dirname, "..", "src", "lib", "db", "generated", "constants.sql");
writeFileSync(outPath, sql);
console.log("Wrote", outPath);
