import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  DIFFICULTY_BASE,
  TASK_COIN_DISCOUNT,
  COMBO_TIERS,
  LEVEL_XP_BASE,
  LEVEL_XP_EXPONENT,
  FREEZE_TOKEN_LEVEL_INTERVAL,
  FREEZE_TOKEN_MAX_BALANCE,
  LEAGUE_TIERS,
  LEAGUE_PROMOTE_TOP,
  LEAGUE_RELEGATE_BOTTOM,
  AVATAR_COLOR_LEVELS,
  TITLE_LEVELS,
  CARD_SKIN_LEVELS,
  QUESTS,
  GOAL_CHECKPOINT_COUNT,
  GOAL_BONUS_PCT,
  GOAL_STAKE_MIN,
  GOAL_TARGET_MIN,
  GOAL_MIN_WINDOW_DAYS,
} from "../src/features/gamification/constants";

/**
 * Mirrors src/features/gamification/constants.ts into SQL so the Postgres
 * RPCs and the tested TS lib can never drift (CLAUDE.md: divergence is a
 * breaking bug). Regenerate with `npm run db:gen-sql` whenever constants.ts
 * changes, then re-apply with `npm run db:apply-sql`.
 */

const difficultyCases = Object.entries(DIFFICULTY_BASE)
  .map(([difficulty, base]) => `    when '${difficulty}' then ${base}`)
  .join("\n");

// COMBO_TIERS is ordered highest-min-first, matching the TS lib's first-match iteration.
const comboCases = COMBO_TIERS.map((tier) => `    when streak >= ${tier.min} then ${tier.mult}`).join("\n");

// Unknown ids fall to 9999 so the RLS gate (caller_level() >= unlock_level) rejects them.
const avatarColorCases = Object.entries(AVATAR_COLOR_LEVELS)
  .map(([id, level]) => `    when '${id}' then ${level}`)
  .join("\n");
const titleCases = Object.entries(TITLE_LEVELS)
  .map(([id, level]) => `    when '${id}' then ${level}`)
  .join("\n");
const cardSkinCases = Object.entries(CARD_SKIN_LEVELS)
  .map(([id, level]) => `    when '${id}' then ${level}`)
  .join("\n");

// Quests: metric/goal/reward and optional event window, mirrored so fn_claim_quest
// validates against the exact same catalog the client shows. Unknown id -> null
// metric (the RPC rejects it); windowless quests -> null from/until.
const questMetricCases = QUESTS.map((q) => `    when '${q.id}' then '${q.metric}'`).join("\n");
const questGoalCases = QUESTS.map((q) => `    when '${q.id}' then ${q.goal}`).join("\n");
const questRewardCases = QUESTS.map((q) => `    when '${q.id}' then ${q.reward}`).join("\n");
const questFromCases = QUESTS.filter((q) => q.activeFrom).map((q) => `    when '${q.id}' then date '${q.activeFrom}'`).join("\n");
const questUntilCases = QUESTS.filter((q) => q.activeUntil).map((q) => `    when '${q.id}' then date '${q.activeUntil}'`).join("\n");
const questFromBody = questFromCases ? `  select case p_id\n${questFromCases}\n    else null::date\n  end;` : `  select null::date;`;
const questUntilBody = questUntilCases ? `  select case p_id\n${questUntilCases}\n    else null::date\n  end;` : `  select null::date;`;

const sql = `-- GENERATED by scripts/gen-sql-constants.ts from src/features/gamification/constants.ts
-- Do not hand-edit. Run \`npm run db:gen-sql\` to regenerate.

create or replace function public.difficulty_base(difficulty text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case difficulty
${difficultyCases}
  end;
$$;

create or replace function public.combo_multiplier(streak int)
returns numeric
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case
${comboCases}
    else 1
  end;
$$;

create or replace function public.task_coins(difficulty text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select round(public.difficulty_base(difficulty) * ${TASK_COIN_DISCOUNT})::int;
$$;

create or replace function public.level_req_for(p_level int)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select round(${LEVEL_XP_BASE} * power(p_level, ${LEVEL_XP_EXPONENT}))::int;
$$;

create or replace function public.level_info(total_xp int)
returns table(level int, into_level int, need int)
language plpgsql
immutable
set search_path = public, pg_catalog
as $$
declare
  v_level int := 1;
  v_remaining int := greatest(0, total_xp);
begin
  while v_remaining >= public.level_req_for(v_level) loop
    v_remaining := v_remaining - public.level_req_for(v_level);
    v_level := v_level + 1;
  end loop;
  return query select v_level, v_remaining, public.level_req_for(v_level);
end;
$$;

create or replace function public.freeze_token_level_interval()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${FREEZE_TOKEN_LEVEL_INTERVAL};
$$;

create or replace function public.freeze_token_max_balance()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${FREEZE_TOKEN_MAX_BALANCE};
$$;

create or replace function public.tokens_earned_between_levels(level_before int, level_after int)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select (level_after / public.freeze_token_level_interval())
       - (level_before / public.freeze_token_level_interval());
$$;

create or replace function public.league_tiers()
returns text[]
language sql
immutable
set search_path = public, pg_catalog
as $$
  select array[${LEAGUE_TIERS.map((t) => `'${t}'`).join(", ")}];
$$;

create or replace function public.league_promote_top()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${LEAGUE_PROMOTE_TOP};
$$;

create or replace function public.league_relegate_bottom()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${LEAGUE_RELEGATE_BOTTOM};
$$;

create or replace function public.avatar_color_unlock_level(p_id text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case p_id
${avatarColorCases}
    else 9999
  end;
$$;

create or replace function public.title_unlock_level(p_id text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case p_id
${titleCases}
    else 9999
  end;
$$;

create or replace function public.card_skin_unlock_level(p_id text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case p_id
${cardSkinCases}
    else 9999
  end;
$$;

create or replace function public.quest_metric(p_id text)
returns text
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case p_id
${questMetricCases}
    else null
  end;
$$;

create or replace function public.quest_goal(p_id text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case p_id
${questGoalCases}
    else 0
  end;
$$;

create or replace function public.quest_reward(p_id text)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case p_id
${questRewardCases}
    else 0
  end;
$$;

create or replace function public.quest_active_from(p_id text)
returns date
language sql
immutable
set search_path = public, pg_catalog
as $$
${questFromBody}
$$;

create or replace function public.quest_active_until(p_id text)
returns date
language sql
immutable
set search_path = public, pg_catalog
as $$
${questUntilBody}
$$;
`;

const outPath = join(__dirname, "..", "src", "lib", "db", "generated", "constants.sql");

// Phase P — staked pledges. These MUST match goals/derived.ts exactly
// (checkpointThreshold / checkpointPayoutTotal / completionBonus); the RPCs are
// authoritative and the UI shows the same numbers, so any drift is a visible lie.
const pledgeSql = `
create or replace function public.goal_checkpoint_count()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${GOAL_CHECKPOINT_COUNT};
$$;

create or replace function public.goal_stake_min()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${GOAL_STAKE_MIN};
$$;

create or replace function public.goal_target_min()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${GOAL_TARGET_MIN};
$$;

create or replace function public.goal_min_window_days()
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ${GOAL_MIN_WINDOW_DAYS};
$$;

-- Completions needed to reach checkpoint p_i (1-based).
-- The 4.0 is load-bearing: with an integer divisor Postgres truncates BEFORE
-- ceil() runs, so ceil() becomes a no-op and target 10 would yield thresholds
-- 2,5,7,10 instead of 3,5,8,10 — paying the first checkpoint one completion
-- early, and disagreeing with Math.ceil in derived.ts.
create or replace function public.goal_checkpoint_threshold(p_target int, p_i int)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select ceil(p_target::numeric * p_i / ${GOAL_CHECKPOINT_COUNT}.0)::int;
$$;

-- CUMULATIVE stake returned after banking p_n checkpoints. An actual payout is
-- always total(n) - total(already_banked), so banking several at once can never
-- drift from banking them one at a time. The final checkpoint trues up the
-- remainder, so all COUNT payouts sum to exactly the stake for any integer
-- stake (50 -> 12,12,12,14) and no coins are created or destroyed.
create or replace function public.goal_checkpoint_payout_total(p_staked int, p_n int)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select case
    when p_n <= 0 then 0
    when p_n >= ${GOAL_CHECKPOINT_COUNT} then p_staked
    else p_n * (p_staked / ${GOAL_CHECKPOINT_COUNT})
  end;
$$;

-- Bonus on top of the returned stake for completing the pledge.
-- Cast to numeric so this rounds half-away-from-zero exactly like JS
-- Math.round on the positive values we use; round(double) would diverge if
-- GOAL_BONUS_PCT ever stops being .5.
create or replace function public.goal_completion_bonus(p_staked int)
returns int
language sql
immutable
set search_path = public, pg_catalog
as $$
  select round(p_staked::numeric * ${GOAL_BONUS_PCT})::int;
$$;
`;

writeFileSync(outPath, sql + pledgeSql);
console.log("Wrote", outPath);
